AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPCId:
    Description: VPC to create the security group into
    Type: String
    Default: 'vpc-0149c9b074b10d3f3'
Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: My security group
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 109.225.83.66/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 109.255.83.66/32
        - IpProtocol: -1
          CidrIp: 10.192.0.0/16
      Tags:
        - Key: Name
          Value: MySecurityGroup
